version: '3.7'

services:
    subscriber:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: pangaea-subscriber-service
        ports:
            - 8081:3000
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules